#!/bin/bash
DIRECTORY=$(dirname "$0")
PROJROOT=$(git rev-parse --show-toplevel)
echo "Changing to ${DIRECTORY}"
cd  "$DIRECTORY" || exit 1
pwd
echo "Run your project here."
cd "$PROJROOT"
go run src/* $@
